theme: jekyll-theme-minimal

title: dc_shield
description: A IFX9201 based Arduino Uno R3 motor shield.
logo: https://github.com/eurovibes/dc_shield/raw/master/images/dc_shield.png
show_downloads: true

github:
  zip_url: downloads/fabrication.zip
  tar_url: downloads/fabrication.tar.gz
